-- =========================================================
-- IT Learning Hub
-- Migration 001
-- Learning System
-- =========================================================


-- =========================================================
-- 1. Profiles
-- =========================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,

    full_name text,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now()
);


-- =========================================================
-- 2. Courses
-- =========================================================

create table if not exists public.courses (
    id bigint generated by default as identity primary key,

    slug text not null unique,

    title text not null,

    description text,

    category_level text not null
        check (category_level in (
            'beginner',
            'intermediate',
            'advanced'
        )),

    icon text,

    is_published boolean not null default true,

    created_at timestamptz not null default now()
);


-- =========================================================
-- 3. Levels
-- =========================================================

create table if not exists public.levels (
    id bigint generated by default as identity primary key,

    course_id bigint not null
        references public.courses(id)
        on delete cascade,

    level_number integer not null
        check (level_number > 0),

    title text not null,

    description text,

    passing_score integer not null default 70
        check (passing_score between 0 and 100),

    is_published boolean not null default true,

    created_at timestamptz not null default now(),

    unique (course_id, level_number)
);


-- =========================================================
-- 4. Lessons
-- =========================================================

create table if not exists public.lessons (
    id bigint generated by default as identity primary key,

    level_id bigint not null
        references public.levels(id)
        on delete cascade,

    lesson_number integer not null
        check (lesson_number > 0),

    title text not null,

    description text,

    content text,

    created_at timestamptz not null default now(),

    unique (level_id, lesson_number)
);


-- =========================================================
-- 5. Questions
-- =========================================================

create table if not exists public.questions (
    id bigint generated by default as identity primary key,

    level_id bigint not null
        references public.levels(id)
        on delete cascade,

    question_text text not null,

    option_a text not null,

    option_b text not null,

    option_c text not null,

    option_d text not null,

    correct_answer text not null
        check (correct_answer in ('A', 'B', 'C', 'D')),

    question_number integer not null
        check (question_number > 0),

    created_at timestamptz not null default now(),

    unique (level_id, question_number)
);


-- =========================================================
-- 6. Lesson Progress
-- =========================================================

create table if not exists public.lesson_progress (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    lesson_id bigint not null
        references public.lessons(id)
        on delete cascade,

    completed boolean not null default false,

    completed_at timestamptz,

    created_at timestamptz not null default now(),

    updated_at timestamptz not null default now(),

    unique (user_id, lesson_id)
);


-- =========================================================
-- 7. Exam Attempts
-- =========================================================

create table if not exists public.exam_attempts (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    level_id bigint not null
        references public.levels(id)
        on delete cascade,

    score integer not null
        check (score between 0 and 100),

    passed boolean not null,

    attempted_at timestamptz not null default now()
);


-- =========================================================
-- 8. Certificates
-- =========================================================

create table if not exists public.certificates (
    id bigint generated by default as identity primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    course_id bigint not null
        references public.courses(id)
        on delete cascade,

    level_id bigint not null
        references public.levels(id)
        on delete cascade,

    certificate_number text not null unique,

    course_title text not null,

    level_title text not null,

    description text,

    score integer
        check (score between 0 and 100),

    issued_at timestamptz not null default now(),

    unique (user_id, level_id)
);


-- =========================================================
-- 9. Indexes
-- =========================================================

create index if not exists idx_levels_course_id
on public.levels(course_id);


create index if not exists idx_lessons_level_id
on public.lessons(level_id);


create index if not exists idx_questions_level_id
on public.questions(level_id);


create index if not exists idx_lesson_progress_user_id
on public.lesson_progress(user_id);


create index if not exists idx_exam_attempts_user_id
on public.exam_attempts(user_id);


create index if not exists idx_exam_attempts_level_id
on public.exam_attempts(level_id);


create index if not exists idx_certificates_user_id
on public.certificates(user_id);


-- =========================================================
-- 10. Enable Row Level Security
-- =========================================================

alter table public.profiles
enable row level security;

alter table public.courses
enable row level security;

alter table public.levels
enable row level security;

alter table public.lessons
enable row level security;

alter table public.questions
enable row level security;

alter table public.lesson_progress
enable row level security;

alter table public.exam_attempts
enable row level security;

alter table public.certificates
enable row level security;


-- =========================================================
-- 11. Profiles Policies
-- =========================================================

create policy "Users can view their own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);


create policy "Users can update their own profile"
on public.profiles
for update
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);


-- =========================================================
-- 12. Courses Policies
-- =========================================================

create policy "Anyone can view published courses"
on public.courses
for select
to anon, authenticated
using (is_published = true);


-- =========================================================
-- 13. Levels Policies
-- =========================================================

create policy "Anyone can view published levels"
on public.levels
for select
to anon, authenticated
using (is_published = true);


-- =========================================================
-- 14. Lessons Policies
-- =========================================================

create policy "Anyone can view lessons"
on public.lessons
for select
to anon, authenticated
using (true);


-- =========================================================
-- 15. Questions Policies
-- =========================================================

create policy "Authenticated users can view questions"
on public.questions
for select
to authenticated
using (true);


-- =========================================================
-- 16. Lesson Progress Policies
-- =========================================================

create policy "Users can view their own lesson progress"
on public.lesson_progress
for select
to authenticated
using (auth.uid() = user_id);


create policy "Users can create their own lesson progress"
on public.lesson_progress
for insert
to authenticated
with check (auth.uid() = user_id);


create policy "Users can update their own lesson progress"
on public.lesson_progress
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);


-- =========================================================
-- 17. Exam Attempt Policies
-- =========================================================

create policy "Users can view their own exam attempts"
on public.exam_attempts
for select
to authenticated
using (auth.uid() = user_id);


create policy "Users can create their own exam attempts"
on public.exam_attempts
for insert
to authenticated
with check (auth.uid() = user_id);


-- =========================================================
-- 18. Certificate Policies
-- =========================================================

create policy "Users can view their own certificates"
on public.certificates
for select
to authenticated
using (auth.uid() = user_id);


-- =========================================================
-- END
-- =========================================================