
/*
 * ============================================
 * IT Learning Hub
 * Migration 002
 * Learning Activity & Streak System
 * ============================================
 */


/*
 * ============================================
 * 1. Learning activity table
 * ============================================
 *
 * One row represents one user's activity
 * on one calendar day.
 *
 * The same user cannot have duplicate rows
 * for the same date.
 */

create table if not exists public.learning_activity (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    activity_date date not null
        default current_date,

    lessons_completed integer not null
        default 0
        check (lessons_completed >= 0),

    minutes_learned integer not null
        default 0
        check (minutes_learned >= 0),

    created_at timestamptz not null
        default now(),

    updated_at timestamptz not null
        default now(),

    constraint learning_activity_user_date_unique
        unique (user_id, activity_date)

);


/*
 * ============================================
 * 2. Indexes
 * ============================================
 *
 * These indexes make dashboard queries
 * faster when retrieving a user's activity.
 */

create index if not exists
    learning_activity_user_id_idx
on public.learning_activity(user_id);


create index if not exists
    learning_activity_activity_date_idx
on public.learning_activity(activity_date);


create index if not exists
    learning_activity_user_date_idx
on public.learning_activity(user_id, activity_date);


/*
 * ============================================
 * 3. Enable Row Level Security
 * ============================================
 */

alter table public.learning_activity
enable row level security;


/*
 * ============================================
 * 4. SELECT policy
 * ============================================
 *
 * Users can see only their own activity.
 */

drop policy if exists
    "Users can view their own learning activity"
on public.learning_activity;


create policy
    "Users can view their own learning activity"

on public.learning_activity

for select

to authenticated

using (
    auth.uid() = user_id
);


/*
 * ============================================
 * 5. INSERT policy
 * ============================================
 *
 * Users can create activity only for
 * their own account.
 */

drop policy if exists
    "Users can create their own learning activity"
on public.learning_activity;


create policy
    "Users can create their own learning activity"

on public.learning_activity

for insert

to authenticated

with check (
    auth.uid() = user_id
);


/*
 * ============================================
 * 6. UPDATE policy
 * ============================================
 *
 * Allows the application to update the
 * current day's activity.
 */

drop policy if exists
    "Users can update their own learning activity"
on public.learning_activity;


create policy
    "Users can update their own learning activity"

on public.learning_activity

for update

to authenticated

using (
    auth.uid() = user_id
)

with check (
    auth.uid() = user_id
);


/*
 * ============================================
 * 7. Updated-at trigger function
 * ============================================
 */

create or replace function
public.update_learning_activity_updated_at()

returns trigger

language plpgsql

as $$
begin

    new.updated_at = now();

    return new;

end;
$$;


/*
 * ============================================
 * 8. Updated-at trigger
 * ============================================
 */

drop trigger if exists
    learning_activity_updated_at
on public.learning_activity;


create trigger
    learning_activity_updated_at

before update
on public.learning_activity

for each row

execute function
public.update_learning_activity_updated_at();


/*
 * ============================================
 * 9. Helper function
 * ============================================
 *
 * Records today's learning activity.
 *
 * If today's row does not exist:
 *     create it.
 *
 * If today's row already exists:
 *     increment the selected counters.
 *
 * This function is SECURITY DEFINER so the
 * application does not need direct UPDATE
 * logic for activity aggregation.
 */

create or replace function
public.record_learning_activity(
    p_lessons_completed integer default 0,
    p_minutes_learned integer default 0
)

returns public.learning_activity

language plpgsql

security definer

set search_path = public

as $$
declare

    result public.learning_activity;

begin

    if auth.uid() is null then

        raise exception 'Authentication required';

    end if;


    if p_lessons_completed < 0 then

        raise exception
            'lessons_completed cannot be negative';

    end if;


    if p_minutes_learned < 0 then

        raise exception
            'minutes_learned cannot be negative';

    end if;


    insert into public.learning_activity (

        user_id,
        activity_date,
        lessons_completed,
        minutes_learned

    )

    values (

        auth.uid(),
        current_date,
        p_lessons_completed,
        p_minutes_learned

    )

    on conflict (
        user_id,
        activity_date
    )

    do update set

        lessons_completed =
            public.learning_activity.lessons_completed
            + excluded.lessons_completed,

        minutes_learned =
            public.learning_activity.minutes_learned
            + excluded.minutes_learned,

        updated_at = now()


    returning *

    into result;


    return result;

end;
$$;


/*
 * ============================================
 * 10. Restrict function execution
 * ============================================
 *
 * The function is intended for authenticated
 * users only.
 */

revoke all
on function public.record_learning_activity(integer, integer)
from public;


grant execute
on function public.record_learning_activity(integer, integer)
to authenticated;

